version: '3.8'

services:
  web:
    build: .
    ports:
      - "3367:3367"
    env_file:
      - .env
    environment:
      - IMAGE_1_PATH=${IMAGE_1_PATH:-images/pusheen-burrito.gif}
      - IMAGE_2_PATH=${IMAGE_2_PATH:-images/pusheen-stormy-eating.gif}
      - API_TOKEN=${API_TOKEN}
      - API_ENDPOINT=${API_ENDPOINT}
      - API_URL=${API_URL:-/api/journal}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
      - PORT=${PORT:-3367}